create environment script for internal shell-script usage

diff --git a/parity-setup.in b/parity-setup.in
--- a/parity-setup.in
+++ b/parity-setup.in
@@ -20,7 +20,7 @@ then
 	PARITYbindir=${SELFDIR}
 	PARITYincludedir=${SELFDIR}
 	CC=${SELFDIR}/parity.gnu.gcc/parity.gnu.gcc
-	AR=${SELFDIR}/parity.gnu.ar/parity.gnu.ar
+	AR=${SELFDIR}/parity.gnu.ar/parity.gnu.ar.in
 else
 	PARITYincludedir=${PARITYlibdir}/include
 	CC=${PARITYbindir}/parity.gnu.gcc
@@ -29,6 +29,8 @@ fi
 
 deflibdir=${PARITYlibdir}
 defsysconfdir=${PARITYsysconfdir}
+
+PARITYheader="# This file is part of ${PACKAGE}-${VERSION}"
 
 usage() {
 	cat <<EOF
@@ -267,7 +269,7 @@ get-supported-sdklibs() {
 	done
 }
 
-get-cflags() {
+get-parityflags() {
 	local vsarch=$(get-vsarch "$*")
 	local vsver=$(get-vsver "$*")
 	case ${vsarch} in
@@ -454,27 +456,25 @@ prune-parityconf() {
 
 	local vsver=$(get-vsver "${chost}")
 	local vsarch=$(get-vsarch "${chost}")
-	local conffile="${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf"
-	local defconffile="${PARITYsysconfdir}/parity.${vsarch}.conf"
+	local conf="${PARITYsysconfdir}/parity.${vsarch}-${vsver}"
+	local defconf="${PARITYsysconfdir}/parity.${vsarch}"
 
-	local empty="# This file is part of ${PACKAGE}-${VERSION}"
-	local noconf="${empty}
+	local confheader="${PARITYheader}
 #
 # PARITY CONFIGURATION for ${vsarch}-${vsver}
-#
-# just a meaningful config parse error
-MSVC ${vsver#msvc} (${vsarch}) is ${reason} (try '${SELF##*/} --enable ${chost}') = true
-"
+#"
+	local noconf="MSVC ${vsver#msvc} (${vsarch}) is ${reason} (try '${SELF##*/} --enable ${chost}')"
 	local defnoconf="${noconf/--enable/--set-default}"
 	local defchost=
 	local ret=0
 
+	local confline
 	if ${setdefault:+:} false
 	then
 		defchost=${chost}
-	elif [[ -s ${DESTDIR}${defconffile} ]]
+	fi
+	if ${defchost:+false} : && [[ -s ${DESTDIR}${defconf}.conf ]]
 	then
-		local confline
 		while read confline
 		do
 			if [[ ${confline} == *"PARITY CONFIGURATION for "* ]]
@@ -483,48 +483,76 @@ MSVC ${vsver#msvc} (${vsarch}) is ${reason} (try '${SELF##*/} --enable ${chost}'
 				defchost=$(get-chost "${defchost}")
 				break
 			fi
-		done < "${DESTDIR}${defconffile}"
+		done < "${DESTDIR}${defconf}.conf"
+	fi
+	if ${defchost:+false} : && [[ -s ${DESTDIR}${defconf}.sh ]]
+	then
+		while read confline
+		do
+			if [[ ${confline} == *"PARITY CONFIGURATION for "* ]]
+			then
+				defchost=${confline#*PARITY CONFIGURATION for }
+				defchost=$(get-chost "${defchost}")
+				break
+			fi
+		done < "${DESTDIR}${defconf}.sh"
 	fi
 	if [[ ${defchost} == "${chost}" ]]
 	then
 		if ${uninstall}
 		then
-			rm -f "${DESTDIR}${defconffile}"
+			rm -f "${DESTDIR}${defconf}.conf" "${DESTDIR}${defconf}.sh"
 		else
-			${noquiet} "Disabling ${defconffile} ..."
+			${noquiet} "Disabling ${defconf} ..."
 			traceon
 			mkdir -p "${DESTDIR}${PARITYsysconfdir}" &&
-			echo "${defnoconf}" > "${DESTDIR}${defconffile}"
+			{
+				echo "${confheader}"
+				echo "${defnoconf} = true"
+			} > "${DESTDIR}${defconf}.conf" &&
+			{
+				echo "${confheader}"
+				echo "echo '${defnoconf}' >&2"
+				echo "false"
+			} > "${DESTDIR}${defconf}.sh" &&
 			if ! traceoff $?
 			then
 				ret=1
-				${noquiet} "Disabling ${defconffile} failed."
+				${noquiet} "Disabling ${defconf} failed."
 			else
-				verbose "Disabling ${defconffile} done."
+				verbose "Disabling ${defconf} done."
 			fi
 		fi
 	fi
 
 	if ${uninstall}
 	then
-		rm -f "${DESTDIR}${conffile}"
+		rm -f "${DESTDIR}${conf}.conf" "${DESTDIR}${conf}.sh"
 		rm -f "${DESTDIR}${PARITYlibdir}"/libparity.runtime.${vsarch}-${vsver}.a
 		rm -f "${DESTDIR}${PARITYlibdir}"/libparity.loader.${vsarch}-${vsver}.a
 		return 0
 	fi
 
-	${noquiet} "Disabling ${conffile} ..."
+	${noquiet} "Disabling ${conf} ..."
 	traceon
 	mkdir -p "${DESTDIR}${PARITYsysconfdir}" &&
-	echo "${noconf}" > "${DESTDIR}${conffile}" &&
+	{
+		echo "${confheader}"
+		echo "${noconf} = true"
+	} > "${DESTDIR}${conf}.conf" &&
+	{
+		echo "${confheader}"
+		echo "echo '${noconf}' >&2"
+		echo "false"
+	} > "${DESTDIR}${conf}.sh" &&
 	echo "${empty}" > "${DESTDIR}${PARITYlibdir}"/libparity.runtime.${vsarch}-${vsver}.a &&
 	echo "${empty}" > "${DESTDIR}${PARITYlibdir}"/libparity.loader.${vsarch}-${vsver}.a
 	if ! traceoff $?
 	then
-		verbose "Disabling ${conffile} failed."
+		verbose "Disabling ${conf} failed."
 		return 1
 	fi
-	verbose "Disabling ${conffile} done."
+	verbose "Disabling ${conf} done."
 	return ${ret}
 }
 
@@ -568,11 +596,11 @@ update-parityconf() {
 
 	local vsver=$(get-vsver "${chost}")
 	local vsarch=$(get-vsarch "${chost}")
-	local cflags=$(get-cflags "${chost}")
+	local parityflags=$(get-parityflags "${chost}")
 
 	(
 		local p
-		noquiet "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf ..."
+		noquiet "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver} ..."
 		tmpdir=${TMPDIR:-/tmp}/parity-setup.${vsarch}-${vsver}.$$
 		rm -rf "${tmpdir}"
 
@@ -581,8 +609,7 @@ update-parityconf() {
 		cd "${tmpdir}" || exit 1
 
 		{
-			echo "
-#
+			echo "#
 # PARITY CONFIGURATION for ${vsarch}-${vsver}
 #
 #  Automatically generated by ${SELF##*/}.
@@ -648,40 +675,55 @@ section windows {
 		} > parity.${vsarch}-${vsver}.conf
 		[[ $? -eq 0 ]] || exit 1
 
+		{
+			echo "#
+# PARITY CONFIGURATION for ${vsarch}-${vsver}
+#
+#  Automatically generated by ${SELF##*/}.
+#  To regenerate, use ${SELF##*/} --enable ${chost}.
+#
+PATH=\"${vcPATH}\${PATH:+:}\${PATH}\" export PATH
+LIB=\"$(cygpath -mp "${vcLIB}")\${LIB:+;}\${LIB}\" export LIB
+INCLUDE=\"$(cygpath -mp "${vcINCLUDE}")\${INCLUDE:+;}\${INCLUDE}\" export INCLUDE
+"
+		} > parity.${vsarch}-${vsver}.sh
+		[[ $? -eq 0 ]] || exit 1
+
 		unset PARITY_CONFIG
 
 		verbose "Compiling ${PARITYlibdir}/libparity.runtime.${vsarch}-${vsver}.a ..."
-		"${DESTDIR}${CC}" -mparityconf= ${cflags} -I"${DESTDIR}${PARITYincludedir}"/parity.runtime -c "${DESTDIR}${PARITYlibdir}"/parity.runtime/*.c "${DESTDIR}${PARITYlibdir}"/parity.runtime/*.cpp &&
-		"${DESTDIR}${AR}" cr libparity.runtime.${vsarch}-${vsver}.a *.o
+		"${DESTDIR}${CC}" -mparityconfdir=. ${parityflags} -I"${DESTDIR}${PARITYincludedir}"/parity.runtime -c "${DESTDIR}${PARITYlibdir}"/parity.runtime/*.c "${DESTDIR}${PARITYlibdir}"/parity.runtime/*.cpp &&
+		"${DESTDIR}${AR}" -mparityconfdir=. ${parityflags} cr libparity.runtime.${vsarch}-${vsver}.a *.o
 		traceoff $? || exit 1
 		verbose "Compiling ${PARITYlibdir}/libparity.runtime.${vsarch}-${vsver}.a done."
 
 		verbose "Compiling ${PARITYlibdir}/libparity.loader.${vsarch}-${vsver}.a ..."
 		traceon
-		"${DESTDIR}${CC}" -mparityconf= ${cflags} -I"${DESTDIR}${PARITYincludedir}"/parity.loader -I"${DESTDIR}${PARITYincludedir}"/parity.runtime -c "${DESTDIR}${PARITYlibdir}"/parity.loader/Loader*.c &&
-		"${DESTDIR}${AR}" cr libparity.loader.${vsarch}-${vsver}.a Loader*.o
+		"${DESTDIR}${CC}" -mparityconfdir=. ${parityflags} -I"${DESTDIR}${PARITYincludedir}"/parity.loader -I"${DESTDIR}${PARITYincludedir}"/parity.runtime -c "${DESTDIR}${PARITYlibdir}"/parity.loader/Loader*.c &&
+		"${DESTDIR}${AR}" -mparityconfdir=. ${parityflags} cr libparity.loader.${vsarch}-${vsver}.a Loader*.o
 		traceoff $? || exit 1
 		verbose "Compiling ${PARITYlibdir}/libparity.loader.${vsarch}-${vsver}.a done."
 
 		traceon
 		mkdir -p "${DESTDIR}${PARITYsysconfdir}" &&
 		mv -f libparity.runtime.${vsarch}-${vsver}.a libparity.loader.${vsarch}-${vsver}.a "${DESTDIR}${PARITYlibdir}"/ &&
-		mv -f parity.${vsarch}-${vsver}.conf "${DESTDIR}${PARITYsysconfdir}"/parity.${vsarch}-${vsver}.conf
+		mv -f parity.${vsarch}-${vsver}.conf parity.${vsarch}-${vsver}.sh "${DESTDIR}${PARITYsysconfdir}"/
 		traceoff $? || exit 1
 
 		if ${setdefault:+:} false
 		then
 			traceon
-			cp -f "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf" "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}.conf"
+			cp -f "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf" "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}.conf" &&
+			cp -f "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}-${vsver}.sh" "${DESTDIR}${PARITYsysconfdir}/parity.${vsarch}.sh"
 			traceoff $? || exit 1
 		fi
 	)
 	if [[ $? -ne 0 ]]
 	then
-		noquiet "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf failed."
+		noquiet "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver} failed."
 		return 1
 	fi
-	verbose "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver}.conf done."
+	verbose "Creating ${PARITYsysconfdir}/parity.${vsarch}-${vsver} done."
 	return 0
 }
 
@@ -869,6 +911,82 @@ parityconf-install() {
 	do
 		prune-parityconf --reason="disabled" --set-default "${chost}"
 	done
+	echo "${PARITYheader}
+#
+# load parity environment identified by argv0 argvN...
+
+__parityenv_confdir=\"${PARITYsysconfdir}\"
+__parityenv_args=()
+
+__parityenv_arg=\${0##*/}
+__parityenv_arch=x86
+__parityenv_verspec=
+
+while test \"\${__parityenv_arg#*-}\" != \"\${__parityenv_arg}\"
+do
+	case \${parityenv_argv0} in
+	x86_64-*)
+		__parityenv_arch=x64
+		;;
+	winntmsvc*|msvc*)
+		__parityenv_arg=\${__parityenv_arg#winnt}
+		__parityenv_arg=\${__parityenv_arg#msvc}
+		__parityenv_major=\${__parityenv_arg%%[^0-9]*}
+		case \${__parityenv_major} in
+		[0-9]|[0-9][0-9])
+			__parityenv_arg=\${__parityenv_arg#\${__parityenv_major}}
+			__parityenv_arg=\${__parityenv_arg#.}
+			__parityenv_minor=\${__parityenv_arg%%[^0-9]*}
+			case \${__parityenv_minor} in
+			[0-9]) __parityenv_verspec=-\${__parityenv_major}.\${__parityenv_minor} ;;
+			*)     __parityenv_verspec=-\${__parityenv_major}.0 ;;
+			esac
+			;;
+		esac
+		;;
+	esac
+	__parityenv_arg=\${__parityenv_arg#*-}
+done
+
+for __parityenv_arg in \"\$@\"
+do
+	case \${__parityenv_arg} in
+	-mparityconfdir=*)
+		__parityenv_confdir=\${__parityenv_arg#-mparityconfdir=}
+		;;
+	-m32)
+		__parityenv_arch=x86
+		;;
+	-m64)
+		__parityenv_arch=x64
+		;;
+	-mmsvc*)
+		__parityenv_verspec=-\${__parityenv_arg#-m}
+		;;
+	*)
+		__parityenv_args=( \"\${__parityenv_args[@]}\" \"\${__parityenv_arg}\" )
+		;;
+	esac
+done
+
+set -- \"\${__parityenv_args[@]}\"
+
+if [[ -r \"\${__parityenv_confdir}/parity.\${__parityenv_arch}\${__parityenv_verspec}.sh\" ]]
+then
+	if . \"\${__parityenv_confdir}/parity.\${__parityenv_arch}\${__parityenv_verspec}.sh\"
+	then
+		unset __parityenv_confdir __parityenv_args __parityenv_arg __parityenv_arch __parityenv_verspec
+		true
+	else
+		unset __parityenv_confdir __parityenv_args __parityenv_arg __parityenv_arch __parityenv_verspec
+		false
+	fi
+else
+	echo \"Invalid MSVC version specified (\${__parityenv_verspec}).\" >&2
+	unset __parityenv_confdir __parityenv_args __parityenv_arg __parityenv_arch __parityenv_verspec
+	false
+fi
+" > "${DESTDIR}${PARITYsysconfdir}/parity-environment"
 	return 0
 }
 
@@ -878,7 +996,8 @@ parityconf-uninstall() {
 	do
 		prune-parityconf --uninstall --reason="uninstalled" --set-default "${chost}"
 	done
-	return 0
+	rm -f "${DESTDIR}${PARITYsysconfdir}/parity-environment"
+	return $?
 }
 
 traceon() { :; }
